# Generated by Django 3.0 on 2021-08-17 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appAgua', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tesorero',
            name='usuarioTesorero',
        ),
    ]
